### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by vicentebolea**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

The scipy dependency version differs depending on the python version, we cannot translate this in a conda recipe of a noarch package (noarch packages can't have selectors) thus we should let go older python versions. We need this fix for publishing nrtk-explorer.

### CODE REVIEW

**Comment by barry-ravichandran** [comment]
@bjrichardwebster Need your input here as well.

@vicentebolea `nrtk` and `pybsm`  are currently supporting python versions 3.8 and above. If we modify the host version of `pybsm`, that would affect `nrtk` as  well.

**Comment by vicentebolea** [comment]
> .

Yes, I am not very well verse in conda forge but it seems that there is no other way (maybe other than making the package not noarch). The current state makes this package unusable as a dependency.

Here is how you can do this with a non noarch pkg: https://github.com/conda-forge/staged-recipes/pull/26184/files

**Comment by barry-ravichandran** [comment]
> > .
> 
> Yes, I am not very well verse in conda forge but it seems that there is no other way (maybe other than making the package not noarch). The current state makes this package unusable as a dependency.
> 
> Here is how you can do this with a non noarch pkg: https://github.com/conda-forge/staged-recipes/pull/26184/files

I'll try to make some changes to the `nrtk-explorer` recipe.

**Comment by vicentebolea** [comment]
I just noticed that the reason that we do not see this error in this package is that noarch package just tests with the latest python, while arch packages (such as nrtk-explorer) tests with all the supported python versions.

**Comment by barry-ravichandran** [comment]
@conda-forge-admin, please rerender

**Comment by barry-ravichandran** [comment]
@vicentebolea  PTAL at the current state. I think the proposed changes to this recipe should resolve the issues you are having with `nrtk-explorer`.

FYI, I've started a similar PR for `nrtk` : https://github.com/conda-forge/nrtk-feedstock/pull/8

**Pull request merged**
